name: deploy

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: "v0.88.0"

      - name: Build Web
        run: hugo --minify

      - name: Deploy Web
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUGO }}
          publish_dir: ./public
          external_repository: echotrue/echotrue.github.io
          publish_branch: master
          commit_message: ${{ github.event.head_commit.message }}
